### ISSUE TITLE
Support for mmol/l is millimoles/liter measurement.

### ISSUE THREAD

**Issue by xitation** [StephenBlackWasAlreadyTaken/DexDrip#40]
Hi There,

Wondering if there are plans to also support the mmol/l glucose measurements. This measurement is widely used outside of the USA.

Conversion from mg/dl is trivial: http://www.faqs.org/faqs/diabetes/faq/part1/section-9.html
Simply divide by 18 or multiply by 0.055.

Thanks.

Jon

**Comment by StephenBlackWasAlreadyTaken** [comment]
It's already in there!

**Comment by xitation** [comment]
Sorry my bad, I've only been able to view screenshots so far, I should have asked first :)

**Comment by StephenBlackWasAlreadyTaken** [comment]
No worries!
