### ISSUE TITLE
Correct Graph but BG Number and tendency is incorrect

### ISSUE THREAD

**Issue by dirkfabisch** [StephenBlackWasAlreadyTaken/DexDrip#54]
The graph is in accordance with the values shown by the meter.
But the number reported above the graph as well as the tendency is not correct

For example:
Graph shows a value round about 100 and is more or less unchanged since an hour.
Nevertheless the number shown above shows HIGH and a double arrow down or up.
(High alarm is set to 270)

**Comment by StephenBlackWasAlreadyTaken** [comment]
Hey, these are the predictive values, unfortunately when there is a lot of sensor noise they don't do so well. I'm looking into better ways to determine which points should hold how much weight in determining a good prediction but you are correct that these values won't sound alarms or anything like that, only actual readings will. 

If you pull the latest from master there is an option in settings to turn the predictions off and only display actual readings

**Comment by StephenBlackWasAlreadyTaken** [comment]
Also, when you see that check your bg data table to see if there are duplicate readings. Those cause the predictions a lot of trouble

**Comment by dirkfabisch** [comment]
I installed already the latest version an disabled the predictions. So the values and tendency must come from the raw values. I will check for duplicate readings, when I get access to the mobile from my wife.

**Comment by StephenBlackWasAlreadyTaken** [comment]
oh, with predictions off that would be quite strange, do you use mmol?

On Thu, Jan 29, 2015 at 10:26 AM, Dirk Fabisch <notifications@github.com>
wrote:

> I installed already the latest version an disabled the predictions. So the
> values and tendency must come from the raw values. I will check for
> duplicate readings, when I get access to the mobile from my wife.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StephenBlackWasAlreadyTaken/DexDrip/issues/54#issuecomment-72043134>
> .
>



-- 


Stephen Black

Software Engineer


  ShopKeep | 800.820.9814

       shopkeep.com | facebook <https://www.facebook.com/ShopKeepPOS>
twitter <https://twitter.com/shopkeep> linkedin
<http://www.linkedin.com/company/shopkeep-pos>

**Comment by dirkfabisch** [comment]
We use mg

**Comment by dirkfabisch** [comment]
Somehow the tick at "Display Predictive Values" was again set. So we take a close look again on the numbers and tendency and I will create a new issue if needed.
